# Generated by Django 4.1.2 on 2022-12-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
