# Generated by Django 4.1.2 on 2022-12-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_alter_course_picture_alter_student_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='odigo',
            new_name='codigo',
        ),
        migrations.AddField(
            model_name='teacher',
            name='codigo',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
