# Generated by Django 4.1.2 on 2022-12-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='eli', max_length=255),
            preserve_default=False,
        ),
    ]
