# Generated by Django 4.1.2 on 2022-12-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.TextField(),
        ),
    ]
