# Generated by Django 4.1.2 on 2022-12-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.TextField(null=True),
        ),
    ]
