# Generated by Django 4.1.2 on 2022-12-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0010_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
