# Generated by Django 4.1.2 on 2022-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0011_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
