# Generated by Django 4.1.2 on 2023-01-10 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0012_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptions',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
