# Generated by Django 4.1.2 on 2023-01-11 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0013_inscriptions_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptions',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.course'),
        ),
        migrations.AlterField(
            model_name='inscriptions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='matricula.student'),
        ),
    ]
