# Generated by Django 4.1.2 on 2023-02-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0014_alter_inscriptions_course_alter_inscriptions_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='aula@aula.aula', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='formacion',
            field=models.CharField(default='National University', max_length=255),
            preserve_default=False,
        ),
    ]
