# Generated by Django 4.1.2 on 2023-02-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0015_teacher_email_teacher_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='picture',
            field=models.TextField(null=True),
        ),
    ]
