# Generated by Django 4.1.2 on 2023-02-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0016_teacher_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.TextField(default='https://www.freepik.es/fotos-premium/retrato-sonriente-mujer-corporativa-mirar-tableta-digital-trabajo-posicion-encima-fondo-blanco_22658045.htm#from_view=detail_alsolike'),
            preserve_default=False,
        ),
    ]
